name: Daily Railway Server Scheduler

on:
  workflow_dispatch:
  schedule:
    # Starts daily at 9:00 AM IST (3:30 AM UTC)
    - cron: '30 3 * * *'
    # Stops daily at 9:00 PM IST (15:30 UTC)
    - cron: '30 15 * * *'

jobs:
  control-railway:
    runs-on: ubuntu-latest
    steps:
      - name: Start/Stop Railway App
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          PROJECT_ID: your_project_id_here
          SERVICE_ID: your_service_id_here
        run: |
          ACTION=$(if [ "$(date +'%H')" -eq 3 ]; then echo "start"; else echo "stop"; fi)
          curl -X POST "https://backboard.railway.app/graphql/v2" \
            -H "Authorization: Bearer $RAILWAY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "mutation ControlService($input: ControlServiceInput!) { controlService(input: $input) { success } }",
              "variables": {
                "input": {
                  "projectId": "'"$PROJECT_ID"'",
                  "serviceId": "'"$SERVICE_ID"'",
                  "action": "'"$ACTION"'"
                }
              }
            }'
